CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('启用', '禁用')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    stock INTEGER NOT NULL CHECK(stock >= 0),
    price REAL NOT NULL CHECK(price >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
